version: "3"
   
services:
  db:
    image: postgres
    ports:
      - "54320:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=BC1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123987
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

