# Generated by Django 3.2.3 on 2021-05-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blockChain',
            fields=[
                ('last_hash', models.CharField(blank=True, max_length=256)),
                ('id', models.CharField(blank=True, max_length=256, primary_key=True, serialize=False)),
                ('Nonce', models.CharField(blank=True, max_length=256)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
