# Generated by Django 3.2.3 on 2021-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='block_position',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
